{% set name = "chainladder" %}
{% set version = "0.8.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chainladder-{{ version }}.tar.gz
  sha256: 346c8a71d5d7188b22203da9a49ff35f93e00129bf17b2ea2f45ccc7bd5588ac

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - joblib
    - python
    - numpy >=1.12
    - pandas >=0.23
    - scikit-learn >=0.23
    - scipy
    - matplotlib
    - numba >0.54
    - sparse >=0.9
    - dill
    - patsy

test:
  imports:
    - chainladder
    - chainladder.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/casact/chainladder-python
  summary: Chainladder Package - P&C Loss Reserving package
  license: MPL-2.0
  # License file manually packaged. See https://github.com/casact/chainladder-python/pull/102
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbogaardt
