{% set name = "chainladder" %}
{% set version = "0.8.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/casact/{{ name }}-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8cc5fb29e81ff0a47d94a5d5d3d42e742aef6966cb52897a8b5e13169531a738

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - joblib
    - scipy
    # https://github.com/casact/chainladder-python/blob/238db2237081f387c3ce7c19ada7aae434e77e03/docs/library/releases.md?plain=1#L65
    - numpy >=2
    - pandas >=2.0
    - scikit-learn >=1.4.2
    - numba >0.54
    # Upper bound added due to issue below (_slicing.py is removed in 0.16)
    # ModuleNotFoundError: No module named 'sparse._slicing'
    - sparse >=0.9,<0.16
    - matplotlib-base
    - dill
    - patsy

test:
  source_files:
    - chainladder/methods/tests
    - chainladder/core/tests
    - chainladder/adjustments/tests
    - chainladder/utils/tests
    - chainladder/workflow/tests
    - chainladder/tails/tests
    - conftest.py
  imports:
    - chainladder
    - chainladder.core
  commands:
    - pip check
    - pytest chainladder/methods/tests
    # skipping test to run in jupyter notebook
    - pytest chainladder/core/tests -k "not test_heatmap_render"  # [not win]
    - pytest chainladder/core/tests -k "not test_heatmap_render" --ignore="chainladder/core/tests/test_triangle.py"  # [win]
    - pytest chainladder/adjustments/tests
    - pytest chainladder/utils/tests
    - pytest chainladder/workflow/tests --ignore="chainladder/workflow/tests/test_voting.py" --ignore="chainladder/workflow/tests/test_predict.py"
    - pytest chainladder/tails/tests
  requires:
    - pip
    - pytest
    - lxml
    - jinja2
    - polars  # [not win]

about:
  home: https://github.com/casact/chainladder-python
  summary: Chainladder Package - P&C Loss Reserving package
  description: |
    The chainladder package was built to be able to handle all of your actuarial needs in python. It consists of
    popular actuarial tools, such as triangle data manipulation, link ratios calculation, and IBNR estimates with both
    deterministic and stochastic models.
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  doc_url: https://chainladder-python.readthedocs.io
  dev_url: https://github.com/casact/chainladder-python

extra:
  recipe-maintainers:
    - jbogaardt
