{% set name = "chainladder" %}
{% set version = "0.8.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/casact/chainladder-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fa865233a70cf47d515a6e488982ff7e985c98cbbd05908e4947f0972ab6f30b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  # skip py39 because of missing sparse
  skip: True  # [py<39 or s390x]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - joblib
    - python
    - numpy >=1.12
    - pandas >=0.23
    - scikit-learn >=0.23
    - scipy
    - matplotlib-base
    - numba >0.54
    - sparse >=0.9
    - dill
    - patsy

test:
  source_files:
    - chainladder/methods/tests
    - chainladder/core/tests
    - chainladder/adjustments/tests
    - chainladder/utils/tests
    - chainladder/workflow/tests
    - chainladder/tails/tests
    - conftest.py
  imports:
    - chainladder
    - chainladder.core
  commands:
    - pip check
    - pytest chainladder/methods/tests
    # skipping test to run in jupyter notebook
    - pytest chainladder/core/tests -k "not test_heatmap_render"  # [not win]
    - pytest chainladder/core/tests -k "not test_heatmap_render" --ignore="chainladder/core/tests/test_triangle.py"  # [win]
    - pytest chainladder/adjustments/tests
    - pytest chainladder/utils/tests
    - pytest chainladder/workflow/tests --ignore="chainladder/workflow/tests/test_voting.py" --ignore="chainladder/workflow/tests/test_predict.py"
    - pytest chainladder/tails/tests
  requires:
    - pip
    - pytest
    - lxml
    - jinja2
    - polars  # [not win]

about:
  home: https://github.com/casact/chainladder-python
  summary: Chainladder Package - P&C Loss Reserving package
  description: |
    The chainladder package was built to be able to handle all of your actuarial needs in python. It consists of
    popular actuarial tools, such as triangle data manipulation, link ratios calculation, and IBNR estimates with both
    deterministic and stochastic models.
  license: MPL-2.0
  license_family: MOZILLA
  # License file manually packaged. See https://github.com/casact/chainladder-python/pull/102
  license_file: LICENSE
  doc_url: https://chainladder-python.readthedocs.io
  dev_url: https://github.com/casact/chainladder-python

extra:
  recipe-maintainers:
    - jbogaardt
